- README.md
- main.tf
- modules/storage/bucket/main.tf
- modules/storage/bucket/outputs.tf
- modules/storage/bucket/variables.tf
- modules/storage/main.tf
- modules/storage/outputs.tf
- modules/storage/pubsub/main.tf
- modules/storage/pubsub/outputs.tf
- modules/storage/pubsub/variables.tf
- modules/storage/variables.tf
- outputs.tf
> refactor: storage module

- .gitignore
- examples/byob/main.tf
- main.tf
- modules/service_accounts/main.tf
- modules/service_accounts/variables.tf
Gives the service account `storage.objectAdmin` permissions to the bucket
> chore: Add permissions to service account for BYOB

- README.md
- main.tf
- variables.tf
...also updates Kubernetes TF version.
> feat: Add local restore option

- README.md
- examples/public-dns-with-cloud-dns/main.tf
- examples/public-dns-with-cloud-dns/variables.tf
- main.tf
- variables.tf
- Adding code saving env variable to google terraform and passing to Kubernetes deployment
> feat: Adds code saving env variable

- README.md
- versions.tf
This updates the google provider to v4.82
> feat: Update google provider

- README.md
- modules/app_gke/outputs.tf
- outputs.tf
Output the cluster name on resource creation.
> feat: Add Google Container Cluster Name to outputs

- modules/app_lb/https/main.tf
fix: Fix ssl certificate recreation
> fix: Fix ssl certificate recreation

- README.md
- main.tf
Update terraform-wandb-kubernetes to v.1.13.0
> feat: Update terraform-wandb-kubernetes

- main.tf
bump the controller image tag and re add the operator chart version
> fix: Bump controller image and readd chart version

- deployment-size.tf
Increase minimum node count to 3 for small, medium, and large t-shirt sizes
> chore(backend): Make minimum nodes for t-shirts '3'

- README.md
- main.tf
- variables.tf
Add passthrough for weave, parquet, and gorilla env vars in addition to global.
> fix(dev): Add passthrough for env vars

- modules/service_accounts/main.tf
> fix: Stackdriver SA regex

- main.tf
This is not needed for our current setup
> fix: Cleanup unneeded otel configs

- .github/workflows/tf-lint.yaml
Configure tflint & tf format pipelines along with fixing any issues
> chore: Configure tflint & tf format pipelines

- main.tf
We need to add service accounts for anything that will be accessing the bucket.
> fix: Adding missing service account

- README.md
> chore: Add migration note

- CHANGELOG.md
- README.md
- main.tf
- variables.tf
This reverts commit 691034df2b007d01108d0f8fac611d9ef4ed2d32.
> revert: INFRA-383 toggle for core-managed redis

- NOTICE
- README.md
- main.tf
- variables.tf
- INFRA-673 apply cache_size tag to AKS cluster
- empty
> fix: Tag cluster managed K8S with cache_size

- main.tf
> chore: Passthrough size

- README.md
- main.tf
- variables.tf
> feat: GKE Cluster Labels
