- modules/app_gke/main.tf
- modules/database/main.tf
Once the cluster is created with a default node pool and if we run a terraform apply after, it results in a forced replacement of the default node pool as it interprets the metadata for the node config specifically `disable-legacy-endpoints` has changed. Explicitly adding this metadata to the node config resolves the error.
More info:
https://github.com/hashicorp/terraform-provider-google/issues/3230
https://github.com/hashicorp/terraform-provider-google/issues/2626
> feat: Add disable legacy endpoints

- modules/app_gke/main.tf
The terraform plan:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
~ update in-place
Terraform will perform the following actions:
~ resource "google_container_node_pool" "default" {
id                          = "projects/tmp-terraform-permissions/locations/europe-west2-a/clusters/tf-perms-gcp-cluster/nodePools/default-pool-charming-wildcat"
name                        = "default-pool-charming-wildcat"
~ node_config {
~ image_type        = "COS" -> "COS_CONTAINERD"
tags              = []
}
}
~ resource "kubernetes_service" "service" {
id                     = "default/wandb"
~ metadata {
~ annotations      = {
- "cloud.google.com/neg" = jsonencode(
{
- ingress = true
}
) -> null
}
name …
```
> fix: Update node pool image type

- README.md
- main.tf
- modules/database/variables.tf
- variables.tf
The module defaults the MySQL version to the `8_0_29`, which is not supported by GCP anymore, and during the deployment, the following error comes up.
```
│ Error: Error, failed to create instance tf-perms-gcp-actual-mastiff: googleapi: Error 400: Invalid request: Database version (MYSQL_8_0_29) is deprecated.., invalid
```
The current default version for the `8_0` is the `0_0_26`.
https://cloud.google.com/sql/docs/mysql/db-versions
The idea is to test and validate the downtime time to upgrade the DB for the next minor version, `8_0_30`, considering that it will cause downtime according to the documentation.
https://cloud.google.com/sql/docs/mysql/upgrade-minor-db-version#minor-ver-upgrade
`the instance is restarted during the operation, which causes downtime.`
From Terraform perspective, …
> fix: Update mysql version

- README.md
- examples/public-dns-with-cloud-dns/main.tf
- examples/public-dns-with-cloud-dns/variables.tf
- main.tf
- modules/database/main.tf
- modules/database/outputs.tf
- modules/database/variables.tf
- variables.tf
Switch to enable the MySQL connection via GCP Cloud Proxy with native SSL using the `cloudsql://` in the connection string
> chore: Enable MySQL connection ssl

- README.md
- examples/byob/variables.tf
- examples/public-dns-with-cloud-dns/main.tf
- examples/public-dns-with-cloud-dns/variables.tf
- main.tf
- modules/app_lb/main.tf
- modules/app_lb/url_map/main.tf
- modules/app_lb/url_map/variables.tf
- modules/app_lb/variables.tf
- variables.tf
This PR  **requires** that a value be **explicitly** provided for `allowed_inbound_cidrs`. To allow all inbound connections, the value `["*"]` should be used; this is the value set in the root of the module. To restrict access to specific IPs and/or IP ranges, use CIDR notation:
```
allowed_inbound_cidrs = [ "x.x.x.x/32", "x.x.x.x/24" ]
```
This change is also reflected in the examples.
> feat: Require inbound cidrs be set explicitly

- README.md
- variables.tf
This PR amends the resource requests to half what the resource limits are. With requests = limits, k8s isn't able to spinup new pods if there are existing pods on the node.
> feat: Amend resource limits

- README.md
- variables.tf
This PR amends the resource requests to reasonable values based on behavior seen in the wild, and sets limits to null.
> fix: Amend resource requests and limits

- README.md
- modules/app_gke/outputs.tf
- outputs.tf
This pr outputs additional information about the GKE cluster.
> fix: Enable additional GKE outputs

- examples/byob/variables.tf
chore: Remove unused var from BYBO example
> fix: Remove unused var from BYBO example

- deployment-size.tf
- examples/public-dns-with-cloud-dns/main.tf
- examples/public-dns-with-cloud-dns/variables.tf
- main.tf
This PR merges changes that ensure a Redis cluster is created when `create_redis` is set to `true` in the examples. It also sets the default db size to 6g, which is = the size of the "small" standard size Redis instance.
> fix: Fix Redis Tier

- README.md
- main.tf
- modules/app_gke/variables.tf
This PR passes through env vars specific to certain services to the Helm chart used to install W&B.
> fix: Pass through env vars for services

- examples/public-dns-with-cloud-dns/README.md
Added required and renamed values to the example tfvars
- `allowed_inbound_cidrs` is a required variable
- `domain` seems to have renamed to `domain_name`
> docs: Update README.md for public-dns-with-cloud-dns example

- main.tf
fixing:
`The true and false result expressions must have consistent types. The 'true' value includes object attribute "caCert", which is absent in the 'false' value.`
> fix: Consistent object type for redis

- README.md
- main.tf
- modules/app_gke/main.tf
- modules/app_gke/variables.tf
- modules/service_accounts/main.tf
- modules/service_accounts/outputs.tf
- modules/service_accounts/variables.tf
- outputs.tf
- variables.tf
stackdriver = {
install = true
stackdriver = {
projectId = data.google_client_config.current.project
serviceAccountName = var.service_account_name
}
serviceAccount = { annotations = { "iam.gke.io/gcp-service-account" = module.service_accounts.monitoring_role } }
}
> feat: Added service account name in stackdriver conf

- README.md
- main.tf
- modules/private_link/main.tf
- modules/private_link/outputs.tf
- modules/private_link/script.sh
- modules/private_link/variables.tf
- outputs.tf
- variables.tf
- versions.tf
This Pr has been tested for a upgrade scenario as well as a fresh setup scenario. before this we need to publish helm chart.
PR: https://github.com/wandb/helm-charts/pull/102
Required provider upgrade 
terraform init -upgrade
terraform plan/apply
> feat: Added support for GCP Private Service Connect

- README.md
- main.tf
- modules/app_gke/main.tf
- modules/service_accounts/main.tf
- modules/service_accounts/variables.tf
- variables.tf
Service Accounts in GCP need to be mapped to the SA's in the Kubernetes Cluster. 
https://github.com/wandb/helm-charts/pull/178
Requires helm chart 0.15.0 to work with `create_workload_identity` = `true` for parts of the application.
> feat!: Service Account Mapping

- README.md
- examples/public-dns-with-cloud-dns/main.tf
- examples/public-dns-with-cloud-dns/variables.tf
- main.tf
- outputs.tf
- variables.tf
```
Terraform will perform the following actions:
<= data "google_compute_forwarding_rules" "all" {
+ id    = (known after apply)
+ rules = (known after apply)
}
~ resource "helm_release" "wandb" {
id                         = "wandb-cr"
~ metadata                   = [
- {
...
- values         = jsonencode(
{
- name = "wandb"
- spec = <<-EOT
...
"bucket":
"name": "andrew-levin-gcp-intense-goblin"
"path": ""
"provider": "gcs"
"cloudProvider": "gcp"
...
}
Plan: 0 to add, 1 to change, 0 to destroy.
```
The new helm release spec wasn't shown when running `terraform apply`, but the updates are propagated to the deployment as expected:
- when `bucket_path` was NOT specified, when I exec'd to the wandb-app pod, I saw
```
wandb@wandb-app-65d8cb96-m7jb5:~$ env | grep -i bucket …
```
> feat: Add optional path var for instance level bucket path

- README.md
- main.tf
- modules/clickhouse/main.tf
- modules/clickhouse/output.tf
- modules/clickhouse/variables.tf
- modules/networking/main.tf
- outputs.tf
- variables.tf
Add a ClickHouse terraform module to setup GCP Private Service Connect as described [here](https://clickhouse.com/docs/en/manage/security/gcp-private-service-connect).
This change will have no impact unless `clickhouse_private_endpoint_service_name` is specified.
If the clickhouse_private_endpoint_service_name is specified, then the region of the clickhouse instance should be provided with clickhouse_region.
if the clickhouse private endpoint service name is specified, the endpoint id will be an output variable to simplify manual integration with clickhouse.
> feat: Add support for Private Service Connect to ClickHouse

- modules/clickhouse/main.tf
- modules/clickhouse/variables.tf
- modules/redis/main.tf
- outputs.tf
Enable subscription for key updates
```
Terraform will perform the following actions:
...
~ resource "google_redis_instance" "default" {
id                       = "projects/playground-111/locations/us-central1/instances/andrew-levin-gcp-two-redis"
name                     = "andrew-levin-gcp-two-redis"
~ redis_configs            = {
+ "notify-keyspace-events" = "K$"
}
...
Plan: 0 to add, 1 to change, 0 to destroy.
```
After applying the changes, I connected to the redis instance from two terminal windows. In one window I did
```
10.30.0.4:6378> PSUBSCRIBE __keyspace@0__:*
Reading messages... (press Ctrl-C to quit)
1) "psubscribe"
2) "__keyspace@0__:*"
3) (integer) 1
```
then in another I did
```
10.30.0.4:6378> SET testKey testValue
OK
```
then in the first window I saw the update come …
> feat: Configure notify-keyspace-events for redis

- modules/database/main.tf
- modules/database/variables.tf
Based on the [docs](https://cloud.google.com/sql/docs/mysql/flags#:~:text=binlog_row_value_options), it should be a lowercase string 
```
Error: Error, failed to create instance sa-gcp-social-walrus: googleapi: Error 400: Value requested is not valid. Failed to set binlog_row_image: MINIMAL was not an expected string., invalidFlagValue
with module.wandb.module.database.google_sql_database_instance.default,
on .terraform/modules/wandb/modules/database/main.tf line 47, in resource "google_sql_database_instance" "default":
47: resource "google_sql_database_instance" "default" {
```
After fixing it the DB creation went through.
> fix: Fix database instance flag

- README.md
- main.tf
- variables.tf
Adds a new variable kubernetes_cluster_oidc_issuer_url variable, used to set the internalJWTMap issuer value in our helm charts which defines the mapping of subject to issuer, which is used to authenticate internal service communication.
Also passes the values of the internalJWTMap via tf
> feat: Add internalJWTMap variables used for inter service request authentication

- modules/redis/main.tf
There is a bug where the data source for the locations is sometimes nondeterministic. 
This is a workaround to prevent the deletion and recreation of the redis instance.
> fix: Ignore lifecycle of the locations for redis

- main.tf
- modules/database/main.tf
This update modifies Cloud SQL database flag configurations to ensure compliance with CIS benchmarks.
The "local_infile" database flag controls the server-side LOCAL capability for LOAD DATA statements.
Enabling the "skip_show_database" flag can improve your data security if you have concerns about users being able to see MySQL databases belonging to other users.
> fix: Tune mysql database flags

- README.md
- main.tf
- modules/app_gke/main.tf
- modules/cloud_nat/main.tf
- modules/cloud_nat/variables.tf
- modules/private_link/main.tf
- modules/private_link/outputs.tf
- modules/private_link/variables.tf
- outputs.tf
- variables.tf
- versions.tf
In order for the connection on the PSC consumer side to be available globally, either the global flag on the internal load balancer must be set, or a network load balancer must be used.  Since it is not possible to set the global flag on the internal load balancer via Kubernetes Ingress, an NLB is needed.  To simplify the set for now, that NLB is just pointed to the existing application load balancer.
> fix: Rework the PSC connection to support SSL and be available globally

- modules/database/main.tf
This setting is required for bulk row inserts into the DB
> fix: Reenable local_infile setting for cloudSQL database

- deployment-size.tf
- main.tf
The max k8s nodes setting is controlled in `deployment-size.tf` and is not defaulted in `core/../{aws,azure,google}/*.tf` nor `terraform-{aws,google,azurerm}-wandb/{main,variables}.tf`.
Recent platform incidents demonstrated that mass-pod replacement may fail for max node counts < 4.
> fix: Bump k8s max nodes by 1
